# Copyright 2020 Vectorized, Inc.
#
# Use of this software is governed by the Business Source License
# included in the file licenses/BSL.md
#
# As of the Change Date specified in that file, in accordance with
# the Business Source License, use of this software will be governed
# by the Apache License, Version 2.0

name: Wasm-Dependency
on:
  push:
    tags: 'release-*'
    
jobs:
  publish:
    name: Publish Wasm Dependecy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '12.16.1'
          registry-url: 'https://registry.npmjs.org'

      - name: Check out code
        uses: actions/checkout@v2

      - name: publish
        run: |
          npm install
          VERSION=$(echo ${{ github.ref }} | sed 's/.*release-//')
          npm run publish:wasm-api $VERSION
        working-directory: src/js
        env:
         NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
